apiVersion: v1
kind: Secret
metadata:
  name: keycloak
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/service: auth
type: Opaque
stringData:
  admin-username: admin
  admin-password: <supersecretpassword>
  management-username: management
  management-password: <supersecretpassword>